title : John Martin
tagline:
author :
  name : John Martin
  email : johnjmartiniv@gmail.com
  # github : username
  twitter : johnjmartiniv
  # feedburner : feedname


# production_url : http://fourthjohn.com
# logo:

# url:         http://fourthjohn.com
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     ['Gemfile', 'Gemfile.lock', 'README.md', 'wercker.yml']
timezone:    nil

# Show future posts
future:      true
show_drafts: false
limit_posts: 0
pygments:    true

relative_permalinks: true
permalink: /academy/:title
paginate_path: 'page:num'
paginate: 10

markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "<!--more-->"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
lsi:         false

collections:
  - portfolio

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:

  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: none
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false
